name: CI
on:
  - pull_request
  - push
jobs:
  phpunit:
    name: "PHPUnit (PHP: ${{ matrix.php-versions }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions:
          - 8.0
          - 8.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
          tools: pecl
          extensions: swoole
      - name: Setup MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE DATABASE psx;" -uroot -proot
          mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'test1234';" -uroot -proot
      - name: Composer install
        run: composer install --no-interaction --no-ansi --no-progress
      - name: Run Swoole
        run: cd public && DB=mysql php index.php &
      - name: Wait
        run: sleep 4
      - name: Run PHPUnit
        run: SEND=external DB=mysql vendor/bin/phpunit
